Sprint 1/step 1
kspshnik/react-burger pull request #1
Opened 2021-12-17 02:07 UTC by kspshnik

Все задачи первого этапа выполнены.

2021-12-17 08:30 UTC, grishbar requested changes
Отличная работа, круто, что все сделал на функциональных компонентах, отлично описал propTypes, код написан чисто и легко читается. Есть несколько моментов, которые надо исправить для принятия работы:

Избавиться от создания функций, переменных, проведения расчетов внутри jsx
Сделать корректные дефолтные значения для переменных состояния
Удалить все консоль логи
Донастроить eslint или же полнсостью избавиться от его зависимостей

В целом уже очень качественная работа, давай поправим все эти замечания, и будет вобще прекрасно.

2021-12-17 08:30 UTC, grishbar commented on package.json
> +    "eslint-plugin-react-hooks": "^4.3.0",
`надо исправить`
так  и не понял получилось у тебя настроить конфиг для еслинта или нет, потому что в пулл реквесте файла .eslintrc я не вижу, и соотвественно локально в твоем проекте у меня линтер не работает, если не получилось донастроить, то удали все зависимости если же донастроил, то в пуллреквесте должен быть файл .eslintrc

если нужна помощь, то вот самый короткий путь для настройки eslint - запустить команду `npm i eslint-config-airbnb eslint-plugin-jsx-a11y --save-dev`
далее надо создать файлик `.eslintrc` в корне проекта куда надо записать:
```
{
    "extends": [
      "react-app",
      "airbnb",
      "plugin:jsx-a11y/recommended"
    ],
    "plugins": [
      "jsx-a11y"
    ],
    "rules": {
      "semi": 0,
      "react/jsx-filename-extension": [1, { "extensions": [".js", ".jsx", "tsx"] }]
    }
}
```

2021-12-17 08:30 UTC, grishbar commented on src/components/app-header/app-header.jsx
> +    <header className={headerStyles.header} >
`отлично`
хорошо, что используешь семантические теги

2021-12-17 08:30 UTC, grishbar commented on src/components/app-header/app-header.module.css
> +  height: var(--header__height);
`отлично`
классное использование css переменных, поможет допускать меньше ошибок и держать проект в одном стиле

2021-12-17 08:30 UTC, grishbar commented on src/components/app/app.jsx
> +  const [ingredients, setIngredients] = useState({});
`надо исправить`
по дефолту у тебя тут должно быть null или undefined а не пустой объект, так как так намного проще будет обрабатывать есть у тебя какие то данные сейчас в объекте или нет. Ну и просто логически, если у тебя в объекте ничего не лежит, то он и должен быть null а если пришли ингриденты но там пришел пустой объект, то для этого объекта ничего не поменяется, что не совсем ожидаемо

2021-12-17 08:30 UTC, grishbar commented on src/components/app/app.jsx
> +  console.log(`Добавляем ингредиент с id = '${id}!'`);
`надо исправить`
не забывай удалять console.log после завершения разработки, в продакшен коде, console.log быть не должно

2021-12-17 08:30 UTC, grishbar commented on src/components/app/app.jsx
> +    console.error(`Нет ингредиента с id = '${id}'!!!`);
`можно лучше`
в таких случаях принято выкидывать ошибку, а не писать что то в консоль. Так как зачастую все приложение обернуто какой нибудь библиотекой для обработки ошибок, и выкидывая ошибко она отловится и обработается, а с console.error ты никак не провзимодействуешь в твоем приложении

2021-12-17 08:30 UTC, grishbar commented on src/components/app/app.jsx
> +  console.log(`Тип добавляемого ингредиента: '${ingredients[id]?.type}'.`)
`надо исправить`
пройдись пожалуйста  по всему проекту, и удали console.logи

2021-12-17 08:30 UTC, grishbar commented on src/components/app/app.jsx
> +      <ingredientsContext.Provider value={ingredients}>
`отлично`
круто, что уже сейчас знаешь, что такое контекст реакта и воспользовался им, отличное место для него

2021-12-17 08:30 UTC, grishbar commented on src/components/app/app.jsx
> +          <BurgerConstructor order={order} minusCallback={(ingr) => {removeIngredient(ingr)}} />
`надо исправить`
[нельзя создавать функции внутри jsx](https://qastack.ru/programming/36677733/why-shouldnt-jsx-props-use-arrow-functions-or-bind), это плохо влияет на производительность, и не [рекомендуется разработчиками реакта](https://ru.reactjs.org/docs/faq-functions.html)

2021-12-17 08:30 UTC, grishbar commented on src/components/app/app.module.css
> +  max-height: calc(100vh - var(--header__height));
`можно лучше`
calc предпочтительнее избегать в верстке, так как в 90% случаях, когда ты его используешь можно обойтись без него, если его приходится использовать, вероятней всего что то делаешь не так и можно сделать все намного проще и надежней

2021-12-17 08:30 UTC, grishbar commented on src/components/burger-constructor/burger-constructor.jsx
> +    if (!!ingredients && Object.keys(ingredients).length !== 0) {
`надо исправить`
так как ingredients у тебя по дефлоту объект, то тут !!ingredients всегда будет true, о чем я и говорил, поэтому заведи пожалуйста там null или undefined по дефолту, тогда не придется такую сложную проверку писать

2021-12-17 08:30 UTC, grishbar commented on src/components/burger-constructor/burger-constructor.jsx
> +      }
`можно лучше`
делаешь лишнее действие , можно сразу найти булку и смотреть нашлось что то или нет

2021-12-17 08:30 UTC, grishbar commented on src/components/burger-constructor/burger-constructor.jsx
> +          </ul>
`надо исправить`
кажется это должно быть отдельным компонентом, или по крайней мере вынесено в функцию

2021-12-17 08:30 UTC, grishbar commented on src/components/burger-constructor/burger-constructor.jsx
> +            </p>
`надо исправить`
старайся не создавать никаких объектов и не делать никаких расчетов в jsx это мешает реакту корректно оценивать когда ему нужно ререндирться, а когда нет. Вынеси сумму в переменную в компоненте, также отличное место для использования [useMemo](https://ru.reactjs.org/docs/hooks-reference.html#usememo)

2021-12-17 08:30 UTC, grishbar commented on src/components/burger-ingredients/burger-ingredients.jsx
> +  }, [ingredients]);
`можно лучше`
круто, что реализовал подсвечивание активного таба при скролле, но обрати внимание, что бывают моменты, когда два таба светятся активными, такого быть не должно

2021-12-17 08:30 UTC, grishbar commented on src/components/burger-ingredients/burger-ingredients.jsx
> +            </ul>
`надо исправить`
это тоже надо либо вынести в функцию либо в отдельный компонент

2021-12-17 08:30 UTC, grishbar commented on src/components/burger-ingredients/burger-ingredients.jsx
> +          <div ref={mainsWatchRef}>
`надо исправить`
обрати внимание, что ты тут трижды дублируешь код для соусов булок и начинок, подумай как сделать так, чтобы этого дублирования не было

2021-12-17 13:52 UTC, kspshnik commented on src/components/app/app.jsx
> +  const [ingredients, setIngredients] = useState({});
ESLint настроен, ошибки линтера исправлены.

2021-12-17 13:52 UTC, kspshnik commented on src/components/app/app.jsx
> +  console.log(`Добавляем ингредиент с id = '${id}!'`);
Все отладочные console.log() удалены.

2021-12-17 13:52 UTC, kspshnik commented on src/components/app/app.jsx
> +  console.log(`Тип добавляемого ингредиента: '${ingredients[id]?.type}'.`)
Fixed.

2021-12-17 13:53 UTC, kspshnik commented on src/components/app/app.jsx
> +      <ingredientsContext.Provider value={ingredients}>
;-) Ну я выпускник 18 потока Web.

2021-12-17 13:58 UTC, kspshnik commented on src/components/app/app.jsx
> +          <BurgerConstructor order={order} minusCallback={(ingr) => {removeIngredient(ingr)}} />
Fixed.

2021-12-17 14:05 UTC, kspshnik commented on src/components/burger-constructor/burger-constructor.jsx
> +    if (!!ingredients && Object.keys(ingredients).length !== 0) {
Done.

2021-12-17 14:07 UTC, kspshnik commented on src/components/burger-ingredients/burger-ingredients.jsx
> +  }, [ingredients]);
Да, я это видел. Тут только свой хук писать :(

2021-12-17 16:12 UTC, kspshnik commented on src/components/burger-constructor/burger-constructor.jsx
> +      }
Fixed

2021-12-17 16:12 UTC, kspshnik commented on src/components/burger-constructor/burger-constructor.jsx
> +          </ul>
Done

2021-12-17 16:22 UTC, kspshnik commented on src/components/burger-constructor/burger-constructor.jsx
> +            </p>
Done %)

2021-12-17 16:22 UTC, kspshnik commented on src/components/burger-ingredients/burger-ingredients.jsx
> +  }, [ingredients]);
Не, удалось поправить и так :)

2021-12-17 16:22 UTC, kspshnik commented on src/components/burger-ingredients/burger-ingredients.jsx
> +            </ul>
Fixed.

2021-12-17 16:22 UTC, kspshnik commented on src/components/burger-ingredients/burger-ingredients.jsx
> +          <div ref={mainsWatchRef}>
Done. Выделил компонент и применил трижды :)

2021-12-17 16:23 UTC, kspshnik commented on package.json
> +    "eslint-plugin-react-hooks": "^4.3.0",
Настроил ESLint :о)

2021-12-17 16:24 UTC, kspshnik commented on src/components/app/app.jsx
> +    console.error(`Нет ингредиента с id = '${id}'!!!`);
Консоль лог убрал, на следующем шаге сделаю модалку с ошибкой. Хотя это чисто разрабский ляп - если нет ни одной булки, система не должна такое давать :)

2021-12-17 16:26 UTC, kspshnik commented on src/components/app/app.module.css
> +  max-height: calc(100vh - var(--header__height));
Нас в задании прямо просят "сделать для разной высоты экрана". Да и если честно, calc я очень люблю - удобная штука.

2021-12-18 22:34 UTC, grishbar approved these changes
Прекрасная работа, все критичные замечания исправлены, работу принимаю, удачи в дальнейшем обучении

2021-12-18 22:34 UTC, grishbar commented on src/components/app/app.jsx
> +  };
`можно лучше`
надо просто отфильтровать массив, не взяв в него элемент с текущим id,  метод filter создает и возвращает новый массив, так, что это ок

2021-12-18 22:42 UTC, kspshnik commented on src/components/app/app.jsx
> +  };
Григорий, я сначала так и сделал - и он удаляет _все_ вхождения, а в заказе может быть > 1  экземпляра ингредиента.  Например,  захотел я (клиент) бургер с двойным соусом, а потом решил - нет, и одинарного хватит. Жму на уничтожайку, а оно мне сносит _оба_ экземпляра соуса в заказе :)
Я потому так и сделал сложно - взять все не совпадающие ингредиенты, и _на_ _один_ меньше_ удаляемый.

2021-12-18 22:42 UTC, kspshnik commented
>  удачи в дальнейшем обучении
Спасибо!!

2021-12-18 22:45 UTC, merged