Sprint 2/step 1
kspshnik/react-burger pull request #7
Opened 2022-01-27 23:16 UTC by kspshnik

Все задачи промежуточной сдачи реализованы.

2022-01-28 21:44 UTC, batr94 requested changes
Здравствуйте! Работа выполнена на высоком уровне! Правильно используется контекст для ингредиентов. Подсчёт суммы заказа рассчитывается правильно. Но есть несколько моментов, которые следовало бы исправить:

* После принятия заказа из конструктора заказа не удаляются булки. Так происходит, потому что данные о ней хранятся в отдельном стейте bun
* Если в order передать массив с двумя видами булок, в конструкторе отобразится одна булка, но в цене будут учитываться обе.
* Название пропса no, компонента OrderDetails, следует переименовать, так как название не информативно
* Согласно чек-листу, файл контекста ингредиентов должен находиться в папке services, а не context
* Если нажать на таб ингредиента, то у контейнера ингредиентов и конструктора заказа пропадает верхний отступ http://joxi.ru/V2VkBzGtB0ajwA

2022-01-28 21:44 UTC, batr94 commented on src/components/order-details/order-details.jsx
> +const OrderDetails = ({ no }) => (
Название параметра лучше поменять, так как no переводится как нет
В данном случае лучше использовать название number

2022-01-28 22:02 UTC, kspshnik commented on src/components/order-details/order-details.jsx
> +const OrderDetails = ({ no }) => (
Fixed.

2022-01-28 22:15 UTC, kspshnik commented
> * После принятия заказа из конструктора заказа не удаляются булки. Так происходит, потому что данные о ней хранятся в отдельном стейте bun
Fixed. Сознательно пробросил сеттер стейта в App в хендлер, а не стал возиться с подъёмом стейта или глубоким рефакторингом, т.к. в течение суток всё это счастье переедет в Redux, а там уже автоматом всё получится чисто :)

2022-01-28 22:21 UTC, kspshnik commented
> * Согласно чек-листу, файл контекста ингредиентов должен находиться в папке services, а не context

Fixed.

2022-01-28 22:55 UTC, kspshnik commented
> * Если в order передать массив с двумя видами булок, в конструкторе отобразится одна булка, но в цене будут учитываться обе.

Fixed.  Посчитал стоимость булок отдельно, а стейт заказа фильтрую по принципу "не-булка". В расчёт всегда попадёт только  та булка, которая отображена.

2022-01-29 15:21 UTC, kspshnik commented
> * Если нажать на таб ингредиента, то у контейнера ингредиентов и конструктора заказа пропадает верхний отступ http://joxi.ru/V2VkBzGtB0ajwA

Fixed.

2022-01-29 15:34 UTC, kspshnik commented on src/components/order-details/order-details.jsx
> +const OrderDetails = ({ no }) => (
Все замечания исправлены. Поехали на вторую проверку :))

2022-01-30 12:01 UTC, batr94 commented
Здравствуйте! Отличная работа, Вы исправили все замечания с прошлой проверки. Ваша работа принята!

Желаю успехов в дальнейшем обучении!

2022-01-30 12:07 UTC, merged